### ISSUE TITLE
Spacetime CLI not working in setup

### ISSUE THREAD

**Issue by kevinz917** [clockworklabs/BitCraftMini#58]
Hey 👋🏻! Big fan of BitCraft here and I'm trying to follow the instructions to install this open source version.

 It seems that running spacetime gives you an error command not found: spacetime, and spacetimedb from my understanding is the open source rust crate that allows for all the server infrastructure. Is there a spacetimedb-cli that's missing or a way to add that to PATH so i can run spacetime? Thanks.

**Comment by cloutiertyler** [comment]
@kevinz917 Awesome to hear you're a fan of the game! This is an example project for technology that we haven't released yet. I can keep you updated on when it'll be announced!

**Comment by kevinz917** [comment]
> 

Great, thanks tyler!
